config-version: 2
name: 'mixpanel'
version: '0.13.0'
require-dbt-version: [">=1.3.0", "<2.0.0"]
models:
  mixpanel:
    +schema: mixpanel
    staging:
      +schema: stg_mixpanel
vars:
  mixpanel:
    event_table: "{{ source('mixpanel', 'event') }}"
    event_custom_columns: []     # any custom column names in the source mixpanel.event table to include in mixpanel__event
            # - name: "app_version" <- example format
            #   alias: "app_version_alias"
            #   transform_sql: "cast(app_version as string)"
    event_properties_to_pivot: []     # list of events in mixpanel__event.event_properties (in the source table, event.properties) to pivot out into columns in mixpanel__event
    session_passthrough_columns: []     # choose event columns to pass through to mixpanel__sessions (values taken from first event of session)
    mixpanel_sources: []