name: 'mixpanel_integration_tests'
version: '0.11.0'
config-version: 2
profile: 'integration_tests'

models:
  mixpanel:
    +schema: "{{ 'mixpanel_sqlw_tests' if target.name == 'databricks-sql' else 'mixpanel' }}"
    # +schema: "mixpanel_{{ var('directed_schema','dev') }}" ## To be used for validation testing

vars:
  mixpanel_schema: mixpanel_integration_tests_2
  mixpanel:
    mixpanel_event_identifier: "event"

seeds:
  mixpanel_integration_tests:
    +column_types:
      _fivetran_synced: timestamp
    event:
      +column_types:
        time: timestamp
        distinct_id: "{{ 'varchar(100)'  if target.type in ('redshift', 'postgres') else 'string'}}"
        device_id: "{{ 'varchar(100)'  if target.type in ('redshift', 'postgres') else 'string'}}"

dispatch:
  - macro_namespace: dbt_utils
    search_order: ['spark_utils', 'dbt_utils']