name: 'mixpanel_integration_tests'
version: '0.9.0'
config-version: 2
profile: 'integration_tests'
vars:
  mixpanel_schema: 22_mixpanel_integration_tests_2
  mixpanel:
    mixpanel_event_identifier: "event"
seeds:
  mixpanel_integration_tests:
    +column_types:
      _fivetran_synced: timestamp
    event:
      +column_types:
        time: timestamp
        distinct_id: "{{ 'varchar(100)'  if target.type in ('redshift', 'postgres') else 'string'}}"
        device_id: "{{ 'varchar(100)'  if target.type in ('redshift', 'postgres') else 'string'}}"

dispatch:
  - macro_namespace: dbt_utils
    search_order: ['spark_utils', 'dbt_utils']
